from flask import redirect, render_template, request, url_for, session, abort, flash
import psycopg2
import psycopg2.extras
from db import get_db, get_db_visualization
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
import config

class Establishment(object):

	db = None

	@classmethod
	def create_table_with_id(cls,table_name,headers):
		con = get_db()

		query = "DROP TABLE \""+table_name+"\""
		cursor = con.cursor(cursor_factory = psycopg2.extras.DictCursor)
		con.commit()
		query = "CREATE TABLE \""+table_name+"\" (ID int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
		elem = len(headers)
		for header in headers:
			elem = elem - 1
			query = query + "\""+header+"\" VARCHAR(255)"
			if elem != 0:
				query = query +", "
			else: 
				query = query + ")"
		cursor.execute(query)
		con.commit()

		return None

	@classmethod
	def select_all(cls, table_name):
		con = get_db()
		cursor = con.cursor(cursor_factory = psycopg2.extras.DictCursor)
		query = "SELECT * FROM \""+table_name+"\""
		cursor.execute(query)

		return cursor.fetchall()

	@classmethod
	def select_cities(cls):
		con = get_db()
		cursor = con.cursor(cursor_factory = psycopg2.extras.DictCursor)
		query = "SELECT * FROM city ORDER BY localidad asc"
		cursor.execute(query)

		return cursor.fetchall()

	@classmethod
	def select_provinces(cls):
		con = get_db()
		cursor = con.cursor(cursor_factory = psycopg2.extras.DictCursor)
		query = "SELECT * FROM province ORDER BY jurisdiccion asc"
		cursor.execute(query)

		return cursor.fetchall()

	@classmethod
	def select_establishments(cls):
		con = get_db()
		cursor = con.cursor(cursor_factory = psycopg2.extras.DictCursor)
		query = "SELECT * FROM establishment ORDER BY nombre asc"
		cursor.execute(query)

		return cursor.fetchall()

	@classmethod
	def get_cities_by_province(cls, province_id):
		con = get_db()
		cursor = con.cursor(cursor_factory = psycopg2.extras.DictCursor)
		query = "SELECT DISTINCT * FROM city WHERE city.id_provincia='" + str(province_id) + "' ORDER BY localidad asc"
		cursor.execute(query)

		return cursor.fetchall()

	@classmethod
	def get_establishments_by_city(cls, city_id):
		con = get_db()
		cursor = con.cursor(cursor_factory = psycopg2.extras.DictCursor)
		query = "SELECT * FROM establishment WHERE establishment.id_ciudad='" + str(city_id) + "' ORDER BY nombre asc"
		cursor.execute(query)

		return cursor.fetchall()